snpCaller:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/Atlas2_v1.4.1/Atlas-SNP2"
  code: "Atlas-SNP2.rb"
  starter: "/hgsc_software/ruby/ruby-1.9.2/bin/ruby"
snpAnnotator:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/annotation_caller"
  code: "SNPAnnotator.jar"
  starter: "java -jar"
  dbConfigFile: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/annotation_caller/annotationpipeline.config"
snpAnnoToVCF:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/annotation_caller"
  code: "SNPAnnoToVCF.jar"
  starter: "java -jar"
indelCaller:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/Atlas2_v1.4.1/Atlas-Indel2"
  code: "Atlas-Indel2.rb"
  starter: "/hgsc_software/ruby/ruby-1.9.2/bin/ruby"
indelAnnotator:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/annotation_caller"
  code: "IndelAnnotator.jar"
  starter: "java -jar"
  dbConfigFile: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/annotation_caller/annotationpipeline.config"
indelAnnoToVCF:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/annotation_caller"
  code: "IndelAnnoToVCF.jar"
  starter: "java -jar"
VCFanalyzer:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/VCFanalyzer"
  code: "vcfAnalyzer.pl"
  starter: "/hgsc_software/perl/latest/bin/perl"
Mendelian_VCFpost:
  codeDirectory: "/stornext/snfs5/next-gen/Illumina/ipipeV2/components/_CONVERT_BINv2"
  code: "RUNCONVERSION.pl"
  starter: "/hgsc_software/perl/latest/bin/perl"
AtlasVIP:
  BEDfile: "/stornext/snfs5/next-gen/Illumina/ipipeV2/config/SNP_INDEL_VIPlist.bed"
