picard:
  path: "/stornext/snfs5/next-gen/Illumina/ipipeV2/picard/current"
  stringency: "VALIDATION_STRINGENCY=LENIENT"
  tempDir: "TMP_DIR=/space1/tmp"
  maxRecordsInRAM: "MAX_RECORDS_IN_RAM=3000000"
  maxHeapSize: "-Xmx22G"
bwa:
  path: "/stornext/snfs5/next-gen/Illumina/ipipeV2/bwa/bwa_0_5_9/bwa-0.5.9/bwa"
scheduler:
  queue:
    normal:
      maxCores: 8
      maxMemory: 28000
    high:
      maxCores: 8
      maxMemory: 28000
    hptest:
      maxCores: 16
      maxMemory: 28000
    anno:
      maxCores: 1
      maxMemory: 4000
casava:
  bclToFastqPath: "/hgsc_software/casava/CASAVA_v1.8.2/bin/configureBclToFastq.pl"
captureStats:
  codeDirectory: "/stornext/snfs5/next-gen/software/hgsc/capture_stats"
  captureCode: "CaptureStatsBAM5"
sequencers:
  rootDir: "/stornext/snfs0/next-gen/Illumina/Instruments"
lims:
  databaseName: "HGSC"
generateVCF:
  gatkPath: "/hgsc_software/gatk/gatk-1.6.2/GenomeAnalysisTK.jar"
  dbSnpPath: "/users/jy2/workspace/reference/phase2/mapping_resources/ALL.wgs.dbsnp.build135.snps.sites.vcf.gz"
  samtoolsPath: "/stornext/snfs5/next-gen/software/samtools-0.1.7/samtools"
