picard:
  path: "/stornext/snfs5/next-gen/Illumina/ipipeV2/picard/current"
  stringency: "VALIDATION_STRINGENCY=LENIENT"
  tempDir: "TMP_DIR=/space1/tmp"
  maxRecordsInRAM: "MAX_RECORDS_IN_RAM=3000000"
  maxHeapSize: "-Xmx22G"
bwa:
  path: "/stornext/snfs5/next-gen/niravs_scratch/code/bwa_test/bwa_0_5_9/bwa-0.5.9/bwa"
scheduler:
  queue:
    normal:
      maxCores: 8
      maxMemory: 28000
    high:
      maxCores: 8
      maxMemory: 28000
    hptest:
      maxCores: 16
      maxMemory: 28000
casava:
  bclToFastqPath: "/stornext/snfs5/next-gen/Illumina/GAPipeline/CASAVA1_8/CASAVA1_8-Install/bin/configureBclToFastq.pl"
captureStats:
  codeDirectory: "/stornext/snfs5/next-gen/software/hgsc/capture_stats"
  captureCode: "CaptureStatsBAM5"
sequencers:
  rootDir: "/stornext/snfs0/next-gen/Illumina/Instruments"
